### ISSUE TITLE
Option: Use trip_short_name in place of Run #

### ISSUE THREAD

**Issue by hkvlhm** [BlinkTagInc/gtfs-to-html#33] opened 2017-06-16 01:24 UTC
It would be helpful to have the option of displaying the trip_short_name in the column header in place of Run # 1, Run # 2, etc. This makes sense in cases where the agency uses customer-facing numbers for trips.

**Comment by brendannee** [comment] 2017-06-16 23:08
I think we're already attempting to do that here: https://github.com/BlinkTagInc/gtfs-to-html/blob/master/views/timetable/timetable_horizontal.pug#L12

Perhaps its not working as intended - can you link me the GTFS file of an agency that uses trip_short_name and I'll test it out?

**Comment by antrim** [comment] 2017-06-16 23:15
@brendannee This may have been an issue on our side! GTFS Manager 2.0 lost trip_short_name export, and we are adding it back in. So, we that means we can't point to any GTFS data. This is almost certainly a mistake we made.

**Comment by brendannee** [comment] 2017-06-16 23:38
OK - closing this issue.

**Closed by brendannee** 2017-06-16 23:38 UTC
